---
name: EmocionLUZ
description: Nos apasiona crear espacio con Emoción a través de la LUZ.
logo: assets/images/logo_b.png
favicon: assets/images/favicon_w.png
email: isai@emocionluz.com
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  sal:
    name: Isai
    site: https://emocionluz.com
    avatar: "/assets/images/avatar1.jpg"
    bio: Hola, soy Isai, administrador del blog EmocionLUZ, también colaboro en proyectos
      de diseño de iluminación y control.
    email: isai@emocionluz.com
    twitter: https://twitter.com/emocionluz
  jane:
    name: Gerardo
    site: https://emocionluz.com
    avatar: "/assets/images/avatar2.jpg"
    bio: Hola, soy Gerardo, soy arquitecto colaborador de EmociónLUZ y de proyectos
      de diseño de interiores e iluminación.
    email: contacto@emocionluz.com
    twitter: https://twitter.com/emocionluz
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: Isai
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
